In [2]:
from run_once import daterange
from normalise import aggs_to_df
from client import get_aggs_5m
from config import settings
from datetime import datetime

In [3]:
days = [day for day in daterange(settings.START_DATE,settings.END_DATE,days=settings.CHUNK_DAYS)]
days

[(datetime.datetime(2025, 9, 29, 0, 0), datetime.datetime(2025, 10, 6, 0, 0)),
 (datetime.datetime(2025, 10, 6, 0, 0), datetime.datetime(2025, 10, 10, 0, 0))]

In [4]:
symbol = 'INTC'
aggs = get_aggs_5m(symbol,datetime(2025,9,29),datetime(2025,10,6))
aggs

[Agg(open=35.25, high=35.66, low=35.07, close=35.52, volume=234670, vwap=35.4901, timestamp=1759132800000, transactions=2045, otc=None),
 Agg(open=35.54, high=35.71, low=35.5, close=35.64, volume=120336, vwap=35.5643, timestamp=1759133100000, transactions=1242, otc=None),
 Agg(open=35.65, high=35.68, low=35.55, close=35.66, volume=53979, vwap=35.625, timestamp=1759133400000, transactions=613, otc=None),
 Agg(open=35.68, high=35.74, low=35.58, close=35.58, volume=50241, vwap=35.6593, timestamp=1759133700000, transactions=547, otc=None),
 Agg(open=35.58, high=35.58, low=35.55, close=35.55, volume=47234, vwap=35.5575, timestamp=1759134000000, transactions=472, otc=None),
 Agg(open=35.55, high=35.62, low=35.55, close=35.58, volume=23398, vwap=35.5756, timestamp=1759134300000, transactions=335, otc=None),
 Agg(open=35.56, high=35.81, low=35.53, close=35.64, volume=233954, vwap=35.7507, timestamp=1759134600000, transactions=1635, otc=None),
 Agg(open=35.62, high=35.64, low=35.59, close=35.61, volume=19846, vwap=35.6138, timestamp=1759134900000, transactions=283, otc=None),
 Agg(open=35.57, high=35.57, low=35.51, close=35.51, volume=53693, vwap=35.5336, timestamp=1759135200000, transactions=398, otc=None),
 Agg(open=35.52, high=35.55, low=35.34, close=35.35, volume=65320, vwap=35.4541, timestamp=1759135500000, transactions=1054, otc=None),
 Agg(open=35.35, high=35.48, low=35.31, close=35.36, volume=50626, vwap=35.3786, timestamp=1759135800000, transactions=517, otc=None),
 Agg(open=35.35, high=35.39, low=35.27, close=35.27, volume=52042, vwap=35.3146, timestamp=1759136100000, transactions=595, otc=None),
 Agg(open=35.26, high=35.43, low=35.26, close=35.43, volume=29043, vwap=35.3488, timestamp=1759136400000, transactions=397, otc=None),
 Agg(open=35.43, high=35.44, low=35.26, close=35.4, volume=28706, vwap=35.3448, timestamp=1759136700000, transactions=418, otc=None),
 Agg(open=35.41, high=35.43, low=35.18, close=35.23, volume=66213, vwap=35.2836, timestamp=1759137000000, transactions=734, otc=None),
 Agg(open=35.21, high=35.21, low=35.01, close=35.08, volume=79882, vwap=35.0982, timestamp=1759137300000, transactions=878, otc=None),
 Agg(open=35.08, high=35.15, low=34.91, close=34.95, volume=130037, vwap=35.0081, timestamp=1759137600000, transactions=1323, otc=None),
 Agg(open=34.96, high=34.99, low=34.9, close=34.95, volume=49553, vwap=34.947, timestamp=1759137900000, transactions=580, otc=None),
 Agg(open=34.94, high=34.98, low=34.71, close=34.88, volume=216356, vwap=34.8422, timestamp=1759138200000, transactions=1955, otc=None),
 Agg(open=34.87, high=34.89, low=34.78, close=34.84, volume=73862, vwap=34.8365, timestamp=1759138500000, transactions=913, otc=None),
 Agg(open=34.84, high=35.05, low=34.84, close=35.05, volume=64164, vwap=34.9263, timestamp=1759138800000, transactions=697, otc=None),
 Agg(open=35.04, high=35.07, low=34.87, close=34.9, volume=112540, vwap=34.9688, timestamp=1759139100000, transactions=1047, otc=None),
 Agg(open=34.9, high=34.94, low=34.86, close=34.92, volume=19169, vwap=34.9068, timestamp=1759139400000, transactions=308, otc=None),
 Agg(open=34.9, high=34.93, low=34.83, close=34.84, volume=37539, vwap=34.8724, timestamp=1759139700000, transactions=473, otc=None),
 Agg(open=34.86, high=34.96, low=34.86, close=34.94, volume=30529, vwap=34.908, timestamp=1759140000000, transactions=482, otc=None),
 Agg(open=34.92, high=35.09, low=34.92, close=35.07, volume=49360, vwap=34.9952, timestamp=1759140300000, transactions=514, otc=None),
 Agg(open=35.07, high=35.07, low=34.95, close=35, volume=38830, vwap=35.0227, timestamp=1759140600000, transactions=394, otc=None),
 Agg(open=34.99, high=35.06, low=34.99, close=35.04, volume=22205, vwap=35.0266, timestamp=1759140900000, transactions=321, otc=None),
 Agg(open=35.05, high=35.11, low=34.92, close=34.97, volume=40958, vwap=35.0308, timestamp=1759141200000, transactions=514, otc=None),
 Agg(open=34.95, high=35, low=34.91, close=34.98, volume=73195, vwap=34.9569, timestamp=1759141500000, transactions=529, otc=None),
 Agg(open=35, high=35.07, low=35, close=35.03, volume=22129, vwap=35.0392, timestamp=1759141800000, transactions=325, otc=None),
 Agg(open=35.02, high=35.07, low=34.98, close=35.03, volume=45120, vwap=35.0179, timestamp=1759142100000, transactions=470, otc=None),
 Agg(open=35.03, high=35.06, low=35, close=35.05, volume=16953, vwap=35.0218, timestamp=1759142400000, transactions=242, otc=None),
 Agg(open=35.06, high=35.06, low=34.99, close=34.99, volume=15444, vwap=35.0276, timestamp=1759142700000, transactions=243, otc=None),
 Agg(open=34.99, high=35.05, low=34.99, close=35.03, volume=15075, vwap=35.0062, timestamp=1759143000000, transactions=244, otc=None),
 Agg(open=35.03, high=35.1, low=35.03, close=35.1, volume=10964, vwap=35.0602, timestamp=1759143300000, transactions=154, otc=None),
 Agg(open=35.09, high=35.16, low=34.9, close=34.9, volume=229124, vwap=35.0415, timestamp=1759143600000, transactions=2019, otc=None),
 Agg(open=34.9, high=34.94, low=34.84, close=34.86, volume=68906, vwap=34.8777, timestamp=1759143900000, transactions=689, otc=None),
 Agg(open=34.86, high=34.92, low=34.85, close=34.89, volume=27470, vwap=34.8845, timestamp=1759144200000, transactions=279, otc=None),
 Agg(open=34.9, high=34.98, low=34.89, close=34.92, volume=30672, vwap=34.9386, timestamp=1759144500000, transactions=281, otc=None),
 Agg(open=34.92, high=34.95, low=34.88, close=34.91, volume=23072, vwap=34.9143, timestamp=1759144800000, transactions=253, otc=None),
 Agg(open=34.92, high=34.94, low=34.92, close=34.921, volume=7026, vwap=34.9317, timestamp=1759145100000, transactions=127, otc=None),
 Agg(open=34.94, high=34.95, low=34.92, close=34.94, volume=26056, vwap=34.9341, timestamp=1759145400000, transactions=278, otc=None),
 Agg(open=34.94, high=34.94, low=34.8, close=34.86, volume=85558, vwap=34.8578, timestamp=1759145700000, transactions=830, otc=None),
 Agg(open=34.87, high=34.93, low=34.87, close=34.9, volume=26274, vwap=34.9026, timestamp=1759146000000, transactions=268, otc=None),
 Agg(open=34.91, high=34.99, low=34.91, close=34.94, volume=20620, vwap=34.9435, timestamp=1759146300000, transactions=239, otc=None),
 Agg(open=34.95, high=34.96, low=34.89, close=34.94, volume=18124, vwap=34.9271, timestamp=1759146600000, transactions=235, otc=None),
 Agg(open=34.92, high=34.98, low=34.92, close=34.97, volume=19906, vwap=34.9557, timestamp=1759146900000, transactions=163, otc=None),
 Agg(open=35.02, high=35.81, low=34.7299, close=34.9415, volume=2044198.0, vwap=35.0857, timestamp=1759147200000, transactions=9931, otc=None),
 Agg(open=34.95, high=35, low=34.93, close=34.95, volume=72407, vwap=34.9686, timestamp=1759147500000, transactions=510, otc=None),
 Agg(open=34.96, high=35, low=34.94, close=34.96, volume=54107, vwap=34.9581, timestamp=1759147800000, transactions=424, otc=None),
 Agg(open=34.96, high=35, low=34.9208, close=34.9208, volume=55614, vwap=34.9677, timestamp=1759148100000, transactions=624, otc=None),
 Agg(open=34.93, high=34.9359, low=34.85, close=34.89, volume=158723, vwap=34.8777, timestamp=1759148400000, transactions=947, otc=None),
 Agg(open=34.89, high=34.91, low=34.73, close=34.83, volume=224969, vwap=34.8114, timestamp=1759148700000, transactions=1615, otc=None),
 Agg(open=34.83, high=34.86, low=34.74, close=34.74, volume=171279, vwap=34.8073, timestamp=1759149000000, transactions=1053, otc=None),
 Agg(open=34.74, high=34.79, low=34.6, close=34.6, volume=406086, vwap=34.682, timestamp=1759149300000, transactions=2047, otc=None),
 Agg(open=34.6012, high=34.61, low=34.29, close=34.39, volume=776509, vwap=34.4251, timestamp=1759149600000, transactions=4909, otc=None),
 Agg(open=34.399, high=34.63, low=34.38, close=34.6, volume=305062, vwap=34.5242, timestamp=1759149900000, transactions=1368, otc=None),
 Agg(open=34.59, high=34.66, low=34.54, close=34.6, volume=214795, vwap=34.5926, timestamp=1759150200000, transactions=1136, otc=None),
 Agg(open=34.6, high=34.61, low=34.51, close=34.5199, volume=110707, vwap=34.562, timestamp=1759150500000, transactions=1007, otc=None),
 Agg(open=34.51, high=34.58, low=34.41, close=34.48, volume=290516, vwap=34.4818, timestamp=1759150800000, transactions=1612, otc=None),
 Agg(open=34.48, high=34.54, low=34.43, close=34.4488, volume=208639, vwap=34.4786, timestamp=1759151100000, transactions=1375, otc=None),
 Agg(open=34.4403, high=34.5199, low=34.44, close=34.51, volume=100148, vwap=34.4736, timestamp=1759151400000, transactions=754, otc=None),
 Agg(open=34.5198, high=34.63, low=34.51, close=34.5599, volume=169193, vwap=34.5859, timestamp=1759151700000, transactions=1355, otc=None),
 Agg(open=34.55, high=34.59, low=34.52, close=34.55, volume=145549, vwap=34.5539, timestamp=1759152000000, transactions=930, otc=None),
 Agg(open=34.55, high=34.58, low=34.41, close=34.49, volume=226796, vwap=34.501, timestamp=1759152300000, transactions=1853, otc=None),
 Agg(open=34.52, high=34.6, low=33.95, close=34.175, volume=9813359.0, vwap=34.1996, timestamp=1759152600000, transactions=47861, otc=None),
 Agg(open=34.18, high=34.21, low=33.73, close=33.93, volume=6274810.0, vwap=33.8864, timestamp=1759152900000, transactions=30489, otc=None),
 Agg(open=33.93, high=34.3, low=33.85, close=34.295, volume=4067314.0, vwap=34.0797, timestamp=1759153200000, transactions=19624, otc=None),
 Agg(open=34.3, high=34.42, low=34.145, close=34.3201, volume=3550283.0, vwap=34.2626, timestamp=1759153500000, transactions=17132, otc=None),
 Agg(open=34.325, high=34.42, low=34.141, close=34.415, volume=2516788.0, vwap=34.2523, timestamp=1759153800000, transactions=13045, otc=None),
 Agg(open=34.411, high=34.64, low=34.33, close=34.4099, volume=3568422.0, vwap=34.5045, timestamp=1759154100000, transactions=15554, otc=None),
 Agg(open=34.405, high=34.455, low=34.11, close=34.1847, volume=2829723.0, vwap=34.2897, timestamp=1759154400000, transactions=13630, otc=None),
 Agg(open=34.1882, high=34.44, low=34.18, close=34.365, volume=1882579.0, vwap=34.2814, timestamp=1759154700000, transactions=9619, otc=None),
 Agg(open=34.3688, high=34.48, low=34.25, close=34.335, volume=1927927.0, vwap=34.3438, timestamp=1759155000000, transactions=9553, otc=None),
 Agg(open=34.335, high=34.57, low=34.32, close=34.415, volume=2083254.0, vwap=34.481, timestamp=1759155300000, transactions=10092, otc=None),
 Agg(open=34.415, high=34.53, low=34.38, close=34.515, volume=1457467.0, vwap=34.4512, timestamp=1759155600000, transactions=7402, otc=None),
 Agg(open=34.515, high=34.65, low=34.5, close=34.615, volume=2087318.0, vwap=34.564, timestamp=1759155900000, transactions=8980, otc=None),
 Agg(open=34.615, high=34.65, low=34.55, close=34.585, volume=1799825.0, vwap=34.5947, timestamp=1759156200000, transactions=8339, otc=None),
 Agg(open=34.5887, high=34.6, low=34.49, close=34.5701, volume=1471079.0, vwap=34.5475, timestamp=1759156500000, transactions=7460, otc=None),
 Agg(open=34.575, high=34.67, low=34.5, close=34.65, volume=1558710.0, vwap=34.6126, timestamp=1759156800000, transactions=7309, otc=None),
 Agg(open=34.6501, high=34.73, low=34.61, close=34.6314, volume=1876429.0, vwap=34.6777, timestamp=1759157100000, transactions=8369, otc=None),
 Agg(open=34.635, high=34.76, low=34.63, close=34.71, volume=1530709.0, vwap=34.6925, timestamp=1759157400000, transactions=7624, otc=None),
 Agg(open=34.705, high=34.78, low=34.65, close=34.665, volume=1647441.0, vwap=34.7004, timestamp=1759157700000, transactions=6897, otc=None),
 Agg(open=34.665, high=34.93, low=34.64, close=34.905, volume=2333300.0, vwap=34.8318, timestamp=1759158000000, transactions=10295, otc=None),
 Agg(open=34.9038, high=34.99, low=34.7701, close=34.835, volume=2772353.0, vwap=34.8761, timestamp=1759158300000, transactions=10186, otc=None),
 Agg(open=34.835, high=34.88, low=34.55, close=34.685, volume=2209892.0, vwap=34.6908, timestamp=1759158600000, transactions=8954, otc=None),
 Agg(open=34.685, high=34.79, low=34.6017, close=34.715, volume=2023985.0, vwap=34.71, timestamp=1759158900000, transactions=9483, otc=None),
 Agg(open=34.7265, high=34.89, low=34.705, close=34.845, volume=1267599.0, vwap=34.8078, timestamp=1759159200000, transactions=6240, otc=None),
 Agg(open=34.845, high=34.87, low=34.67, close=34.6985, volume=1093676.0, vwap=34.7421, timestamp=1759159500000, transactions=5085, otc=None),
 Agg(open=34.695, high=34.7288, low=34.575, close=34.653739, volume=1412882.0, vwap=34.638, timestamp=1759159800000, transactions=6360, otc=None),
 Agg(open=34.6501, high=34.91, low=34.64, close=34.82, volume=1895806.0, vwap=34.7934, timestamp=1759160100000, transactions=7414, otc=None),
 Agg(open=34.8201, high=34.92, low=34.8, close=34.885, volume=1313333.0, vwap=34.8719, timestamp=1759160400000, transactions=5731, otc=None),
 Agg(open=34.8886, high=35.05, low=34.87, close=34.9186, volume=1870509.0, vwap=34.9612, timestamp=1759160700000, transactions=7433, otc=None),
 Agg(open=34.915, high=34.92, low=34.62, close=34.6945, volume=1272262.0, vwap=34.7491, timestamp=1759161000000, transactions=5058, otc=None),
 Agg(open=34.695, high=34.85, low=34.695, close=34.7968, volume=931537, vwap=34.7787, timestamp=1759161300000, transactions=4493, otc=None),
 Agg(open=34.795, high=34.85, low=34.725, close=34.775, volume=869348, vwap=34.7919, timestamp=1759161600000, transactions=3849, otc=None),
 Agg(open=34.775, high=34.82, low=34.71, close=34.755, volume=727972, vwap=34.7599, timestamp=1759161900000, transactions=3410, otc=None),
 Agg(open=34.7501, high=34.8, low=34.71, close=34.75, volume=659427, vwap=34.7557, timestamp=1759162200000, transactions=3416, otc=None),
 Agg(open=34.755, high=34.85, low=34.74, close=34.815, volume=1074501.0, vwap=34.8008, timestamp=1759162500000, transactions=4282, otc=None),
 Agg(open=34.815, high=34.83, low=34.74, close=34.805, volume=766287, vwap=34.7793, timestamp=1759162800000, transactions=3788, otc=None),
 Agg(open=34.805, high=34.94, low=34.74, close=34.935, volume=1197226.0, vwap=34.8394, timestamp=1759163100000, transactions=4433, otc=None),
 Agg(open=34.93, high=34.97, low=34.72, close=34.735, volume=1071727.0, vwap=34.8248, timestamp=1759163400000, transactions=4814, otc=None),
 Agg(open=34.7211, high=34.76, low=34.57, close=34.58, volume=1311379.0, vwap=34.6432, timestamp=1759163700000, transactions=5084, otc=None),
 Agg(open=34.585, high=34.59, low=34.495, close=34.5101, volume=1517454.0, vwap=34.5418, timestamp=1759164000000, transactions=6698, otc=None),
 Agg(open=34.515, high=34.5899, low=34.42, close=34.5651, volume=1759269.0, vwap=34.4778, timestamp=1759164300000, transactions=6834, otc=None),
 Agg(open=34.5698, high=34.61, low=34.46, close=34.485, volume=1062363.0, vwap=34.5313, timestamp=1759164600000, transactions=4872, otc=None),
 Agg(open=34.485, high=34.61, low=34.48, close=34.505, volume=906717, vwap=34.5508, timestamp=1759164900000, transactions=4720, otc=None),
 Agg(open=34.505, high=34.575, low=34.42, close=34.55, volume=1583624.0, vwap=34.5033, timestamp=1759165200000, transactions=6613, otc=None),
 Agg(open=34.545, high=34.55, low=34.46, close=34.495, volume=688663, vwap=34.5145, timestamp=1759165500000, transactions=3774, otc=None),
 Agg(open=34.495, high=34.545, low=34.48, close=34.495, volume=593408, vwap=34.5093, timestamp=1759165800000, transactions=3773, otc=None),
 Agg(open=34.4951, high=34.63, low=34.48, close=34.545, volume=1270879.0, vwap=34.562, timestamp=1759166100000, transactions=5613, otc=None),
 Agg(open=34.5444, high=34.63, low=34.52, close=34.6281, volume=735962, vwap=34.5694, timestamp=1759166400000, transactions=3824, otc=None),
 Agg(open=34.625, high=34.63, low=34.48, close=34.53, volume=1002474.0, vwap=34.5359, timestamp=1759166700000, transactions=4562, otc=None),
 Agg(open=34.5299, high=34.55, low=34.34, close=34.425, volume=1349330.0, vwap=34.4182, timestamp=1759167000000, transactions=5798, otc=None),
 Agg(open=34.42, high=34.45, low=34.36, close=34.435, volume=1438542.0, vwap=34.4085, timestamp=1759167300000, transactions=5664, otc=None),
 Agg(open=34.44, high=34.44, low=34.35, close=34.39, volume=927912, vwap=34.3908, timestamp=1759167600000, transactions=4644, otc=None),
 Agg(open=34.395, high=34.425, low=34.31, close=34.31, volume=988837, vwap=34.3668, timestamp=1759167900000, transactions=4585, otc=None),
 Agg(open=34.315, high=34.35, low=34.22, close=34.3001, volume=1610620.0, vwap=34.2867, timestamp=1759168200000, transactions=7254, otc=None),
 Agg(open=34.3087, high=34.35, low=34.25, close=34.265, volume=942155, vwap=34.3012, timestamp=1759168500000, transactions=3593, otc=None),
 Agg(open=34.265, high=34.34, low=34.23, close=34.34, volume=1079978.0, vwap=34.2652, timestamp=1759168800000, transactions=4232, otc=None),
 Agg(open=34.335, high=34.48, low=34.32, close=34.4438, volume=1279846.0, vwap=34.4162, timestamp=1759169100000, transactions=4472, otc=None),
 Agg(open=34.45, high=34.6, low=34.385, close=34.5847, volume=1795393.0, vwap=34.5069, timestamp=1759169400000, transactions=5008, otc=None),
 Agg(open=34.59, high=34.615, low=34.51, close=34.565, volume=925278, vwap=34.5638, timestamp=1759169700000, transactions=3958, otc=None),
 Agg(open=34.565, high=34.71, low=34.54, close=34.681, volume=1252602.0, vwap=34.6533, timestamp=1759170000000, transactions=4656, otc=None),
 Agg(open=34.685, high=34.72, low=34.67, close=34.708, volume=830848, vwap=34.6964, timestamp=1759170300000, transactions=3642, otc=None),
 Agg(open=34.7099, high=34.73, low=34.62, close=34.635, volume=996617, vwap=34.6679, timestamp=1759170600000, transactions=4303, otc=None),
 Agg(open=34.64, high=34.76, low=34.6, close=34.7299, volume=1032879.0, vwap=34.6547, timestamp=1759170900000, transactions=4517, otc=None),
 Agg(open=34.725, high=34.82, low=34.725, close=34.815, volume=1161383.0, vwap=34.7854, timestamp=1759171200000, transactions=4628, otc=None),
 Agg(open=34.81, high=34.88, low=34.75, close=34.875, volume=1199117.0, vwap=34.8062, timestamp=1759171500000, transactions=4367, otc=None),
 Agg(open=34.875, high=34.885, low=34.75, close=34.7514, volume=930050, vwap=34.8085, timestamp=1759171800000, transactions=3564, otc=None),
 Agg(open=34.755, high=34.7899, low=34.67, close=34.7562, volume=947482, vwap=34.7206, timestamp=1759172100000, transactions=3978, otc=None),
 Agg(open=34.76, high=34.805, low=34.71, close=34.74, volume=954230, vwap=34.7691, timestamp=1759172400000, transactions=4244, otc=None),
 Agg(open=34.745, high=34.77, low=34.66, close=34.695, volume=730148, vwap=34.6915, timestamp=1759172700000, transactions=3343, otc=None),
 Agg(open=34.69, high=34.74, low=34.658, close=34.7098, volume=631126, vwap=34.695, timestamp=1759173000000, transactions=3736, otc=None),
 Agg(open=34.7042, high=34.72, low=34.6366, close=34.69, volume=982533, vwap=34.6745, timestamp=1759173300000, transactions=4429, otc=None),
 Agg(open=34.6861, high=34.7299, low=34.64, close=34.7122, volume=958212, vwap=34.6766, timestamp=1759173600000, transactions=4330, otc=None),
 Agg(open=34.715, high=34.74, low=34.61, close=34.6529, volume=1061675.0, vwap=34.6601, timestamp=1759173900000, transactions=4831, otc=None),
 Agg(open=34.6501, high=34.715, low=34.6, close=34.6535, volume=1064047.0, vwap=34.6533, timestamp=1759174200000, transactions=5663, otc=None),
 Agg(open=34.655, high=34.73, low=34.62, close=34.725, volume=931271, vwap=34.6706, timestamp=1759174500000, transactions=4260, otc=None),
 Agg(open=34.725, high=34.74, low=34.67, close=34.6701, volume=924229, vwap=34.7006, timestamp=1759174800000, transactions=4074, otc=None),
 Agg(open=34.6731, high=34.68, low=34.61, close=34.63, volume=1361986.0, vwap=34.6343, timestamp=1759175100000, transactions=6281, otc=None),
 Agg(open=34.64, high=34.72, low=34.55, close=34.56, volume=2236412.0, vwap=34.64, timestamp=1759175400000, transactions=9787, otc=None),
 Agg(open=34.565, high=34.57, low=34.46, close=34.47, volume=4379348.0, vwap=34.4987, timestamp=1759175700000, transactions=18605, otc=None),

In [5]:
df = aggs_to_df(symbol,aggs)
df

,symbol,open,high,low,close,volume,vwap,timestamp,transactions,otc,event_time_utc,event_time_local,dt,dt_local
0,INTC,35.2500,35.6600,35.07,35.5200,234670.0,35.4901,1759132800000,2045,None,2025-09-29 08:00:00+00:00,2025-09-29 04:00:00-04:00,2025-09-29,2025-09-29
1,INTC,35.5400,35.7100,35.50,35.6400,120336.0,35.5643,1759133100000,1242,None,2025-09-29 08:05:00+00:00,2025-09-29 04:05:00-04:00,2025-09-29,2025-09-29
2,INTC,35.6500,35.6800,35.55,35.6600,53979.0,35.6250,1759133400000,613,None,2025-09-29 08:10:00+00:00,2025-09-29 04:10:00-04:00,2025-09-29,2025-09-29
3,INTC,35.6800,35.7400,35.58,35.5800,50241.0,35.6593,1759133700000,547,None,2025-09-29 08:15:00+00:00,2025-09-29 04:15:00-04:00,2025-09-29,2025-09-29
4,INTC,35.5800,35.5800,35.55,35.5500,47234.0,35.5575,1759134000000,472,None,2025-09-29 08:20:00+00:00,2025-09-29 04:20:00-04:00,2025-09-29,2025-09-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,INTC,36.7800,36.7800,36.75,36.7800,6896.0,36.7693,1759534500000,112,None,2025-10-03 23:35:00+00:00,2025-10-03 19:35:00-04:00,2025-10-03,2025-10-03
956,INTC,36.7600,36.7799,36.75,36.7600,17337.0,36.7651,1759534800000,94,None,2025-10-03 23:40:00+00:00,2025-10-03 19:40:00-04:00,2025-10-03,2025-10-03
957,INTC,36.7598,36.7600,36.72,36.7200,26450.0,36.7453,1759535100000,133,None,2025-10-03 23:45:00+00:00,2025-10-03 19:45:00-04:00,2025-10-03,2025-10-03
958,INTC,36.7300,36.7500,36.73,36.7400,18253.0,36.7407,1759535400000,88,None,2025-10-03 23:50:00+00:00,2025-10-03 19:50:00-04:00,2025-10-03,2025-10-03
959,INTC,36.7500,36.7500,36.70,36.7298,66277.0,36.7264,1759535700000,185,None,2025-10-03 23:55:00+00:00,2025-10-03 19:55:00-04:00,2025-10-03,2025-10-03

In [13]:
groupby = df.groupby("dt")
groupby

In [14]:
groups = [(dt,group) for dt,group in df.groupby("dt")]
test_group = groups[0][1]
test_group

,symbol,open,high,low,close,volume,vwap,timestamp,transactions,otc,event_time_utc,event_time_local,dt,dt_local
0,INTC,35.2500,35.6600,35.0700,35.5200,234670.0,35.4901,1759132800000,2045,None,2025-09-29 08:00:00+00:00,2025-09-29 04:00:00-04:00,2025-09-29,2025-09-29
1,INTC,35.5400,35.7100,35.5000,35.6400,120336.0,35.5643,1759133100000,1242,None,2025-09-29 08:05:00+00:00,2025-09-29 04:05:00-04:00,2025-09-29,2025-09-29
2,INTC,35.6500,35.6800,35.5500,35.6600,53979.0,35.6250,1759133400000,613,None,2025-09-29 08:10:00+00:00,2025-09-29 04:10:00-04:00,2025-09-29,2025-09-29
3,INTC,35.6800,35.7400,35.5800,35.5800,50241.0,35.6593,1759133700000,547,None,2025-09-29 08:15:00+00:00,2025-09-29 04:15:00-04:00,2025-09-29,2025-09-29
4,INTC,35.5800,35.5800,35.5500,35.5500,47234.0,35.5575,1759134000000,472,None,2025-09-29 08:20:00+00:00,2025-09-29 04:20:00-04:00,2025-09-29,2025-09-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,INTC,34.1200,34.1497,34.0975,34.1400,49605.0,34.1216,1759188900000,165,None,2025-09-29 23:35:00+00:00,2025-09-29 19:35:00-04:00,2025-09-29,2025-09-29
188,INTC,34.1400,34.1400,34.1000,34.1198,13576.0,34.1253,1759189200000,89,None,2025-09-29 23:40:00+00:00,2025-09-29 19:40:00-04:00,2025-09-29,2025-09-29
189,INTC,34.1200,34.1200,34.0500,34.0700,54202.0,34.0698,1759189500000,191,None,2025-09-29 23:45:00+00:00,2025-09-29 19:45:00-04:00,2025-09-29,2025-09-29
190,INTC,34.0794,34.1000,34.0775,34.0800,20094.0,34.0860,1759189800000,129,None,2025-09-29 23:50:00+00:00,2025-09-29 19:50:00-04:00,2025-09-29,2025-09-29
191,INTC,34.0900,34.0900,34.0602,34.0800,54521.0,34.0765,1759190100000,206,None,2025-09-29 23:55:00+00:00,2025-09-29 19:55:00-04:00,2025-09-29,2025-09-29

In [17]:
test_group.iloc[0]

symbol                                   INTC
open                                    35.25
high                                    35.66
low                                     35.07
close                                   35.52
volume                               234670.0
vwap                                  35.4901
timestamp                       1759132800000
transactions                             2045
otc                                      None
event_time_utc      2025-09-29 08:00:00+00:00
event_time_local    2025-09-29 04:00:00-04:00
dt                                 2025-09-29
dt_local                           2025-09-29
Name: 0, dtype: object

In [6]:
for dt,group in df.groupby("dt"):
    print(dt)
    print("-------------------")
    print(group)

2025-09-29
-------------------
    symbol     open     high      low    close    volume     vwap  \
0     INTC  35.2500  35.6600  35.0700  35.5200  234670.0  35.4901
1     INTC  35.5400  35.7100  35.5000  35.6400  120336.0  35.5643
2     INTC  35.6500  35.6800  35.5500  35.6600   53979.0  35.6250
3     INTC  35.6800  35.7400  35.5800  35.5800   50241.0  35.6593
4     INTC  35.5800  35.5800  35.5500  35.5500   47234.0  35.5575
..     ...      ...      ...      ...      ...       ...      ...
187   INTC  34.1200  34.1497  34.0975  34.1400   49605.0  34.1216
188   INTC  34.1400  34.1400  34.1000  34.1198   13576.0  34.1253
189   INTC  34.1200  34.1200  34.0500  34.0700   54202.0  34.0698
190   INTC  34.0794  34.1000  34.0775  34.0800   20094.0  34.0860
191   INTC  34.0900  34.0900  34.0602  34.0800   54521.0  34.0765

         timestamp  transactions   otc            event_time_utc  \
0    1759132800000          2045  None 2025-09-29 08:00:00+00:00
1    1759133100000          1242  None 2025-09-29 08:05:00+00:00
2    1759133400000           613  None 2025-09-29 08:10:00+00:00
3    1759133700000           547  None 2025-09-29 08:15:00+00:00
4    1759134000000           472  None 2025-09-29 08:20:00+00:00
..             ...           ...   ...                       ...
187  1759188900000           165  None 2025-09-29 23:35:00+00:00
188  1759189200000            89  None 2025-09-29 23:40:00+00:00
189  1759189500000           191  None 2025-09-29 23:45:00+00:00
190  1759189800000           129  None 2025-09-29 23:50:00+00:00
191  1759190100000           206  None 2025-09-29 23:55:00+00:00

             event_time_local          dt    dt_local
0   2025-09-29 04:00:00-04:00  2025-09-29  2025-09-29
1   2025-09-29 04:05:00-04:00  2025-09-29  2025-09-29
2   2025-09-29 04:10:00-04:00  2025-09-29  2025-09-29
3   2025-09-29 04:15:00-04:00  2025-09-29  2025-09-29
4   2025-09-29 04:20:00-04:00  2025-09-29  2025-09-29
..                        ...         ...         ...
187 2025-09-29 19:35:00-04:00  2025-09-29  2025-09-29
188 2025-09-29 19:40:00-04:00  2025-09-29  2025-09-29
189 2025-09-29 19:45:00-04:00  2025-09-29  2025-09-29
190 2025-09-29 19:50:00-04:00  2025-09-29  2025-09-29
191 2025-09-29 19:55:00-04:00  2025-09-29  2025-09-29

[192 rows x 14 columns]
2025-09-30
-------------------
    symbol     open     high      low    close    volume     vwap  \
192   INTC  34.0900  34.1500  34.0100  34.0100   49668.0  34.0793
193   INTC  34.0100  34.0200  33.8100  33.8600  101219.0  33.9162
194   INTC  33.8700  33.9600  33.8700  33.9000   45944.0  33.9068
195   INTC  33.9400  33.9600  33.8500  33.8500   30918.0  33.8881
196   INTC  33.8600  33.8600  33.7900  33.8000   61643.0  33.8122
..     ...      ...      ...      ...      ...       ...      ...
379   INTC  33.4500  33.4600  33.4200  33.4500    7672.0  33.4477
380   INTC  33.4500  33.4500  33.4200  33.4200   18728.0  33.4264
381   INTC  33.4200  33.4400  33.4000  33.4300    3472.0  33.4248
382   INTC  33.4299  33.4300  33.3509  33.3509   25170.0  33.3920
383   INTC  33.3600  33.3969  33.3000  33.3200   98866.0  33.3217

         timestamp  transactions   otc            event_time_utc  \
192  1759219200000           979  None 2025-09-30 08:00:00+00:00
193  1759219500000          1127  None 2025-09-30 08:05:00+00:00
194  1759219800000           457  None 2025-09-30 08:10:00+00:00
195  1759220100000           522  None 2025-09-30 08:15:00+00:00
196  1759220400000           746  None 2025-09-30 08:20:00+00:00
..             ...           ...   ...                       ...
379  1759275300000            76  None 2025-09-30 23:35:00+00:00
380  1759275600000            64  None 2025-09-30 23:40:00+00:00
381  1759275900000            41  None 2025-09-30 23:45:00+00:00
382  1759276200000           132  None 2025-09-30 23:50:00+00:00
383  1759276500000           187  None 2025-09-30 23:55:00+00:00

             event_time_local          dt    dt_local
192 2025-09-30 04:00:00-04:00  2025-09-30  2025-09-30
193 2025-09-30 04:05:00-04:00  2025-09-30  2025-09-30
194 2025-09-30 04:10:00-04:00  2025-09-30  2025-09-30
195 2025-09-30 04:15:00-04:00  2025-09-30  2025-09-30
196 2025-09-30 04:20:00-04:00  2025-09-30  2025-09-30
..                        ...         ...         ...
379 2025-09-30 19:35:00-04:00  2025-09-30  2025-09-30
380 2025-09-30 19:40:00-04:00  2025-09-30  2025-09-30
381 2025-09-30 19:45:00-04:00  2025-09-30  2025-09-30
382 2025-09-30 19:50:00-04:00  2025-09-30  2025-09-30
383 2025-09-30 19:55:00-04:00  2025-09-30  2025-09-30

[192 rows x 14 columns]
2025-10-01
-------------------
    symbol     open   high    low    close   volume     vwap      timestamp  \
384   INTC  33.0000  33.23  33.00  33.1900  98463.0  33.1401  1759305600000
385   INTC  33.1800  33.28  33.18  33.2100  48141.0  33.2304  1759305900000
386   INTC  33.2200  33.23  33.10  33.2000  67620.0  33.1824  1759306200000
387   INTC  33.1900  33.19  33.12  33.1700  14769.0  33.1569  1759306500000
388   INTC  33.1600  33.16  33.08  33.0800   9426.0  33.1211  1759306800000
..     ...      ...    ...    ...      ...      ...      ...            ...
571   INTC  35.8397  35.85  35.81  35.8100  26040.0  35.8170  1759361700000
572   INTC  35.8200  35.82  35.79  35.8199  15404.0  35.8071  1759362000000
573   INTC  35.8199  35.84  35.80  35.8400  25773.0  35.8154  1759362300000
574   INTC  35.8397  35.84  35.81  35.8213  12593.0  35.8308  1759362600000
575   INTC  35.8400  35.85  35.75  35.7900  65698.0  35.8045  1759362900000

     transactions   otc            event_time_utc          event_time_local  \
384          1263  None 2025-10-01 08:00:00+00:00 2025-10-01 04:00:00-04:00
385           522  None 2025-10-01 08:05:00+00:00 2025-10-01 04:05:00-04:00
386           461  None 2025-10-01 08:10:00+00:00 2025-10-01 04:10:00-04:00
387           242  None 2025-10-01 08:15:00+00:00 2025-10-01 04:15:00-04:00
388           240  None 2025-10-01 08:20:00+00:00 2025-10-01 04:20:00-04:00
..            ...   ...                       ...                       ...
571           131  None 2025-10-01 23:35:00+00:00 2025-10-01 19:35:00-04:00
572           123  None 2025-10-01 23:40:00+00:00 2025-10-01 19:40:00-04:00
573           176  None 2025-10-01 23:45:00+00:00 2025-10-01 19:45:00-04:00
574           126  None 2025-10-01 23:50:00+00:00 2025-10-01 19:50:00-04:00
575           280  None 2025-10-01 23:55:00+00:00 2025-10-01 19:55:00-04:00

             dt    dt_local
384  2025-10-01  2025-10-01
385  2025-10-01  2025-10-01
386  2025-10-01  2025-10-01
387  2025-10-01  2025-10-01
388  2025-10-01  2025-10-01
..          ...         ...
571  2025-10-01  2025-10-01
572  2025-10-01  2025-10-01
573  2025-10-01  2025-10-01
574  2025-10-01  2025-10-01
575  2025-10-01  2025-10-01

[192 rows x 14 columns]
2025-10-02
-------------------
    symbol     open     high      low    close    volume     vwap  \
576   INTC  36.0300  36.1300  36.0000  36.0900  116477.0  36.0698
577   INTC  36.1000  36.1400  36.0800  36.1000   76220.0  36.1157
578   INTC  36.1000  36.1000  36.0300  36.0400   44809.0  36.0750
579   INTC  36.0400  36.1000  36.0400  36.1000   16059.0  36.0751
580   INTC  36.1000  36.1300  36.0500  36.0900   24298.0  36.0953
..     ...      ...      ...      ...      ...       ...      ...
763   INTC  37.2756  37.3500  37.2700  37.3500   24739.0  37.3156
764   INTC  37.3500  37.3500  37.3000  37.3000   35639.0  37.3213
765   INTC  37.3100  37.3299  37.3000  37.3200   23926.0  37.3091
766   INTC  37.3200  37.3300  37.3000  37.3201   27357.0  37.3113
767   INTC  37.3300  37.3500  37.3207  37.3300   36560.0  37.3401

         timestamp  transactions   otc            event_time_utc  \
576  1759392000000           980  None 2025-10-02 08:00:00+00:00
577  1759392300000           956  None 2025-10-02 08:05:00+00:00
578  1759392600000           571  None 2025-10-02 08:10:00+00:00
579  1759392900000           232  None 2025-10-02 08:15:00+00:00
580  1759393200000           379  None 2025-10-02 08:20:00+00:00
..             ...           ...   ...                       ...
763  1759448100000           201  None 2025-10-02 23:35:00+00:00
764  1759448400000           138  None 2025-10-02 23:40:00+00:00
765  1759448700000           132  None 2025-10-02 23:45:00+00:00
766  1759449000000           136  None 2025-10-02 23:50:00+00:00
767  1759449300000           147  None 2025-10-02 23:55:00+00:00

             event_time_local          dt    dt_local
576 2025-10-02 04:00:00-04:00  2025-10-02  2025-10-02
577 2025-10-02 04:05:00-04:00  2025-10-02  2025-10-02
578 2025-10-02 04:10:00-04:00  2025-10-02  2025-10-02
579 2025-10-02 04:15:00-04:00  2025-10-02  2025-10-02
580 2025-10-02 04:20:00-04:00  2025-10-02  2025-10-02
..                        ...         ...         ...
763 2025-10-02 19:35:00-04:00  2025-10-02  2025-10-02
764 2025-10-02 19:40:00-04:00  2025-10-02  2025-10-02
765 2025-10-02 19:45:00-04:00  2025-10-02  2025-10-02
766 2025-10-02 19:50:00-04:00  2025-10-02  2025-10-02
767 2025-10-02 19:55:00-04:00  2025-10-02  2025-10-02

[192 rows x 14 columns]
2025-10-03
-------------------
    symbol     open     high    low    close   volume     vwap      timestamp  \
768   INTC  37.8300  37.9600  37.57  37.9400  65640.0  37.8460  1759478400000
769   INTC  37.9400  38.0000  37.86  37.9700  64040.0  37.9378  1759478700000
770   INTC  37.9700  37.9900  37.80  37.9600  61223.0  37.8954  1759479000000
771   INTC  37.9600  37.9600  37.80  37.8000  31872.0  37.8882  1759479300000
772   INTC  37.8300  37.9200  37.81  37.8600  30583.0  37.8526  1759479600000
..     ...      ...      ...    ...      ...      ...      ...            ...
955   INTC  36.7800  36.7800  36.75  36.7800   6896.0  36.7693  1759534500000
956   INTC  36.7600  36.7799  36.75  36.7600  17337.0  36.7651  1759534800000
957   INTC  36.7598  36.7600  36.72  36.7200  26450.0  36.7453  1759535100000
958   INTC  36.7300  36.7500  36.73  36.7400  18253.0  36.7407  1759535400000
959   INTC  36.7500  36.7500  36.70  36.7298  66277.0  36.7264  1759535700000

     transactions   otc            event_time_utc          event_time_local  \
768           965  None 2025-10-03 08:00:00+00:00 2025-10-03 04:00:00-04:00
769           798  None 2025-10-03 08:05:00+00:00 2025-10-03 04:05:00-04:00
770           707  None 2025-10-03 08:10:00+00:00 2025-10-03 04:10:00-04:00
771           419  None 2025-10-03 08:15:00+00:00 2025-10-03 04:15:00-04:00
772           395  None 2025-10-03 08:20:00+00:00 2025-10-03 04:20:00-04:00
..            ...   ...                       ...                       ...
955           112  None 2025-10-03 23:35:00+00:00 2025-10-03 19:35:00-04:00
956            94  None 2025-10-03 23:40:00+00:00 2025-10-03 19:40:00-04:00
957           133  None 2025-10-03 23:45:00+00:00 2025-10-03 19:45:00-04:00
958            88  None 2025-10-03 23:50:00+00:00 2025-10-03 19:50:00-04:00
959           185  None 2025-10-03 23:55:00+00:00 2025-10-03 19:55:00-04:00

             dt    dt_local
768  2025-10-03  2025-10-03
769  2025-10-03  2025-10-03
770  2025-10-03  2025-10-03
771  2025-10-03  2025-10-03
772  2025-10-03  2025-10-03
..          ...         ...
955  2025-10-03  2025-10-03
956  2025-10-03  2025-10-03
957  2025-10-03  2025-10-03
958  2025-10-03  2025-10-03
959  2025-10-03  2025-10-03

[192 rows x 14 columns]